version: '3.8'

services:
  frontend:
    image: news-frontend:latest
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:3001
    depends_on:
      - backend

  backend:
    image: news-backend:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=newsapp
      - DB_PASSWORD=password
      - DB_NAME=newsapp
      - NEWS_API_KEY=${NEWS_API_KEY}
      -JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=newsapp
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=newsapp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U newsapp"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:

